name: "Auslöser"
description: "Trigger a workflow_dispatch event for PR comments"
inputs:
  pat:
    description: "Github access token"
    required: true
  workflow:
    description: "Workflow to trigger"
  command:
    description: "slash command which will trigger the workflow"
runs:
  using: "node12"
  main: "dist/index.js"
