name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    name: Handle Slash Commands
    runs-on: ubuntu-latest
    steps:
      - uses: homefully/ausloeser@master
        with:
          pat: ${{ secrets.GITHUB_TOKEN }}
